server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
    #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/pollyanna/springcloud-config.git  #是https不是git

#通过config-server可以连接到git，访问其中的资源以及配置